<a href="https://colab.research.google.com/github/Zabiha11/My_Machine_Learning_Journey/blob/main/Python_Basic_to_Advance_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chapter 2 practice set


Add two numbers

In [ ]:
a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
print(a+b)

Enter 1st number: 3
Enter 2nd number: 7
10


Find remainder when divided by z

In [ ]:
n = int(input("Enter a number to compute remainder: "))
z = int(input("Enter a number to divide by: "))

print(n%z)

Enter a number to compute remainder: 10
Enter a number to divide by: 3
1


Check type of variable assigned using input()

In [ ]:
a = input()
print(type(a))

10
<class 'str'>


compare a and b

In [ ]:
a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
print(a>b)

Enter 1st number: 34
Enter 2nd number: 80
False


Average of two numbers


In [ ]:
a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
print((a+b)/2)

Enter 1st number: 49
Enter 2nd number: 75
62.0


Calculate Square of number generated by user

In [ ]:
n = int(input("Enter a number: "))
print(n*n)

Chapter 3 - Strings ( practice set )

1) name + Greetings

In [ ]:
name = input("Enter your name: ")
print("Good Afternoon, " + name)

Enter your name: zabi
Good Afternoon, zabi


2) Fill in the letter template

In [ ]:
name = input("Enter your name: ")
date = input("Enter date: ")
letter = f'''
Dear {name},
You are selected!
{date}
'''
print(letter)

Enter your name: zabi
Enter date: 21-07-2015

Dear zabi,
You are selected!
21-07-2015



3) Program to detect double space

In [ ]:
sentence = input()
sentence.find("  ")

hi im zabi from pec  vnb


19

4) replace double space with single space from the previous problem

In [ ]:
sentence.replace("  "," ")

'hi im zabi from pec vnb'

5) Program to format the letter

In [ ]:
letter = "Dear Zabi,\nThis python course is nice.\nThanks!"
print(letter)

Dear Zabi,
This python course is nice.
Thanks!


Chapter 4 - List and Tuples ( Practice set )

1) Program to store 7 fruits entered by users

In [ ]:
fruits = []
for i in range(1,8):
  fruits.append(input(f"Enter fruit {i}: "))
print(fruits)

Enter fruit 1: apple
Enter fruit 2: banana
Enter fruit 3: cherry
Enter fruit 4: guava
Enter fruit 5: strawberry
Enter fruit 6: mango
Enter fruit 7: melon
['apple', 'banana', 'cherry', 'guava', 'strawberry', 'mango', 'melon']


2) Accept marks of 6 students and display them in sorted order

In [ ]:
students = []
for i in range(1,7):
  students.append(int(input(f"Enter mark of student {i}: ")))
students.sort()
print(students)

Enter mark of student 1: 2
Enter mark of student 2: 8
Enter mark of student 3: 9
Enter mark of student 4: 5
Enter mark of student 5: 3
Enter mark of student 6: 1
[1, 2, 3, 5, 8, 9]


3) Check that a type cannot be changed in python

In [ ]:
marks = [10, 20, 30]
marks1=tuple(marks)
type(marks1)
print(marks1)
print(marks)

(10, 20, 30)
[10, 20, 30]


4) Sum a List with 4 numbers

In [ ]:
list1 = [10, 20, 30, 40]
print(sum(list1))

100


5) Program to count the number of zeros in the following tuple
a = (7, 0, 8, 0, 0, 9)

In [ ]:
a = (7, 0, 8, 0, 0, 9)
a.count(0)

3

**Chapter 5 Dictionaries and Set**


Example program for dictionaries

In [ ]:
# Sample dictionary
person = {'name': 'Alice', 'age': 25, 'city': 'Paris'}

# get()
print(person.get('name'))       # Output: Alice
print(person.get('country', 'France'))  # Output: France

# keys(), values(), items()
print(person.keys())    # dict_keys(['name', 'age', 'city'])
print(person.values())  # dict_values(['Alice', 25, 'Paris'])
print(person.items())   # dict_items([('name', 'Alice'), ('age', 25), ('city', 'Paris')])

# update()
person.update({'age': 26, 'country': 'France'})
print(person)  # {'name': 'Alice', 'age': 26, 'city': 'Paris', 'country': 'France'}

# pop()
person.pop('city')
print(person)  # {'name': 'Alice', 'age': 26, 'country': 'France'}

# popitem()
person.popitem()  # Removes last item
print(person)

# setdefault()
person.setdefault('email', 'alice@example.com')
print(person)

# clear()
person.clear()
print(person)  # {}


Alice
France
dict_keys(['name', 'age', 'city'])
dict_values(['Alice', 25, 'Paris'])
dict_items([('name', 'Alice'), ('age', 25), ('city', 'Paris')])
{'name': 'Alice', 'age': 26, 'city': 'Paris', 'country': 'France'}
{'name': 'Alice', 'age': 26, 'country': 'France'}
{'name': 'Alice', 'age': 26}
{'name': 'Alice', 'age': 26, 'email': 'alice@example.com'}
{}


In [ ]:
s = { 10, 20, 30}
print(type(s))

<class 'set'>


| Method                       | Description                                                                      |
| ---------------------------- | -------------------------------------------------------------------------------- |
| `add(elem)`                  | Adds an element to the set.                                                      |
| `update(iterable)`           | Adds multiple elements from an iterable (e.g., list, tuple).                     |
| `remove(elem)`               | Removes the specified element; raises `KeyError` if not found.                   |
| `discard(elem)`              | Removes the specified element if present; no error if not found.                 |
| `pop()`                      | Removes and returns an arbitrary element. Raises `KeyError` if the set is empty. |
| `clear()`                    | Removes all elements from the set.                                               |
| `copy()`                     | Returns a shallow copy of the set.                                               |
| `union(set2)`                | Returns a new set with elements from both sets.                                  |
| `intersection(set2)`         | Returns a new set with common elements.                                          |
| `difference(set2)`           | Returns elements in the first set but not in the second.                         |
| `symmetric_difference(set2)` | Returns elements in either set, but not both.                                    |
| `issubset(set2)`             | Checks if the set is a subset of another.                                        |
| `issuperset(set2)`           | Checks if the set is a superset of another.                                      |
| `isdisjoint(set2)`           | Checks if two sets have no elements in common.                                   |


Chapter 5 - Practice Set ( Dictionaries and Sets )

1) Dictionary with key - hindi word and value - english translation

In [ ]:
lang = {
    "naam": "name",
    "Phool": "Flower",
    "Ghar": "Home",
    "Bhai": "Brother",
    "Gulab": "Rose",
    "Dabba": "Box"
}

print(lang.keys())
a = input("Enter hindi word: ")
print(lang.get(a))

dict_keys(['naam', 'Phool', 'Ghar', 'Bhai', 'Gulab', 'Dabba'])
Enter hindi word: khana
None


2) Input 8 numbers and display all unique numbers

In [ ]:
num = set()
for i in range(1,9):
  num.ad4d(int(input(f"Enter number {i}: ")))
print(num)

Enter number 1: 60
Enter number 2: 89
Enter number 3: 37
Enter number 4: 8
Enter number 5: 28
Enter number 6: 89
Enter number 7: 8
Enter number 8: 29
{37, 8, 60, 89, 28, 29}


4) is int(18) and str(18) same

In [ ]:
num = {"18", 18}
print(num)

{18, '18'}


5) Find the length of the string


In [ ]:
s = set()
s.add(20)
s.add(20.0)
s.add('20')
print(s)
len(s)

{20, '20'}


2

Create an empty dictionary, Allow 4 frds to enter their faviorate lang as value

In [ ]:
friends = {
    "zabi": "Python",
    "mus": "Java",
    "Tom": "Java",
    "zabi": "HTML"
}
print(friends)

{'zabi': 'HTML', 'mus': 'Java', 'Tom': 'Java'}


**Chapter 6 - Conditional Expressions ( Practice Set )**

Find Greatest of 4 numbers

In [ ]:
a = int(input("Enter 1: "))
b = int(input("Enter 2: "))
c = int(input("Enter 3: "))
d = int(input("Enter 4: "))
if a>b and a>c and a>d:
  print(f"{a} is greatest")
elif b>a and b>c and b>d:
  print(f"{b} is greatest")
elif c>a and c>b and c>d:
  print(f"{c} is greatest")
else:
  print(f"{d} is greatest")

Enter 1: 1
Enter 2: 4
Enter 3: 6
Enter 4: 8
8 is greatest


Student pass/fail in each subject, overall 40% and 33% in each subject atleast

In [ ]:
sub1 = int(input("Enter marks of sub1: "))
sub2 = int(input("Enter marks of sub2: "))
sub3 = int(input("Enter marks of sub3: "))
if sub1 > 33 and sub2 > 33 and sub3 > 33:
  if (sub1+sub2+sub3)/3 > 40:
    print("Pass")
  else:
    print("Fail")
else:
  print("Fail")

Enter marks of sub1: 40
Enter marks of sub2: 60
Enter marks of sub3: 99
Pass


Program to detect spam comments

In [ ]:
spam_comments = ["Make a lot of money", "Buy now", "Subscribe this", "Click this"]
comment = input("Enter comment: ")
if comment in spam_comments:
  print("Spam")
else:
  print("Not Spam")

Enter comment: Buy now
Spam


username with 10 char or less

In [ ]:
username = input("Enter Username: ")
if len(username) < 10:
  print("less than 10 characters")
else:
  print("more than 10 characters")

Enter Username: zabihamuskan
more than 10 characters


check the given name is in list or not

In [ ]:
name = ["zara", "zabi", "mus", "Tom", "Jerry"]
check = input("Enter name:")
if check in name:
  print("Present")
else:
  print("Not Present")


Enter name:zara
Present


Calculate Grade

In [ ]:
marks = int(input("Enter marks:"))
if marks > 90 and marks <= 100:
  print("Excellent")
elif marks > 80 and marks <= 90:
  print("A")
elif marks > 70 and marks <= 80:
  print("B")
elif marks > 60 and marks <= 70:
  print("C")
elif marks > 50 and marks <= 60:
  print("D")
else:
  print("F")

Enter marks:89
A


is the post talking about harry?

In [ ]:
talking = "Harry"
post = input("Enter post: ")
if talking in post:
  print("Yes")
else:
  print("No")

Enter post: Harry
Yes


**Chapter 7 - Loops in Python (practice set)**

Print Multiplication table

In [ ]:
n = int(input("Enter a number: "))
for i in range(n):
  print(f"{n} * {i+1} = {n*(i+1)}")

Enter a number: 5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25


program to greet all persons name stored in list which starts with "s".

In [ ]:
names = ["zabiha", "musab", "Mota", "Tom", "Pikachu", "sunday"]
for name in names:
  if name.startswith("s"):
    print(f"Hello {name}!")

Hello sunday!


tables using while loop

In [ ]:
n = int(input("Enter a number: "))
i = 1
while(i<=10):
  print(f"{n} X {i} = {n*i}")
  i += 1

Enter a number: 3
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27
3 X 10 = 30


Given number is prime or not

In [ ]:
n = int(input("Enter a number: "))

for i in range(2, int(n/2)+1):
  if(n%i == 0):
    print(f"{n} is not Prime")
    break
  else:
    print(f"{n} is Prime")
    break
else:
  print(f"{n} is prime")


Enter a number: 23
23 is Prime


Sum of first n natural numbers

In [ ]:
n = int(input("Enter a number: "))

i = 0
sum = 0

while(i<=n):
  sum += i
  i += 1

print(f"Sum is: {sum}")

Enter a number: 4
Sum is: 10


Factorial of a number

In [ ]:
n = int(input("Enter a number: "))

fact = 1
i = 1

for num in range(n+1):
  fact *= i
  i += 1

print(f"Factorial of {n} is {fact}")

Enter a number: 4
Factorial of 4 is 120


Print star pattern

In [ ]:
n = int(input("Enter a number: "))
for i in range(1,n+1):
  print("*" * i)
  i += 1

Enter a number: 3
*
**
***


In [ ]:
n = int(input("Enter a value: "))

for i in range(1, n+1):
  print(" " * (n-i), end = "")
  print("*" * (2*i-1), end = "")
  print("")

Enter a value: 3
  *
 ***
*****


In [ ]:
n = int(input("Enter a number: "))
for i in range(1, n+1):
  if(i == 1 or i == n):
    print("*" * n, end = "")
  else:
    print("*", end = "")
    print(" " * (n-2), end = "")
    print("*", end = "")
  print("")

Enter a number: 5
*****
*   *
*   *
*   *
*****


Tables in Reverse

In [ ]:
n = int(input("Enter a number: "))

for i in range(10,0,-1):
  print(f"{n} X {i} = {n*i}")

Enter a number: 4
4 X 10 = 40
4 X 9 = 36
4 X 8 = 32
4 X 7 = 28
4 X 6 = 24
4 X 5 = 20
4 X 4 = 16
4 X 3 = 12
4 X 2 = 8
4 X 1 = 4


**Chapter 8 Functions and Recusion (Practice Set)**

Function to Find Greatest of 3 Numbers

In [ ]:
def greatest(a, b, c):
  if a>b and a>c:
    print(f"{a} is greatest")
  elif b>a and b>c:
    print(f"{b} is greatest")
  else:
    print(f"{c} is greatest")

greatest(10, 20, 30)

30 is greatest


In [ ]:
class Employee:
  def __init__(self, name, dep):
    self.name = name
    self.DEP = dep

emp1 = Employee("Zabi", "CSE")
print(emp1.name)
print(emp1.DEP)

Zabi
CSE


Celcius to Fahrenheit

In [ ]:
def temp(celcius):
  fahrenheit = (celcius * 9/5) + 32
  return fahrenheit

temp(0)


32.0

prevent python function from printing new line at the end

In [ ]:
print("hi ", end = "")
print("Zabiha")

hi Zabiha


Recursive Function to calculate the sum of first natural numbers

In [ ]:
n = int(input("Enter a number: "))
sum = 0
def sum_of_n(num):
  if num == 0:
    return 0
  else:
    return num + sum_of_n(num - 1)
sum_of_n(5)

Enter a number: 5


15

Print Pattern

In [ ]:
n = int(input("Enter a number: "))

def pattern(n):
  if n == 0:
    return
  else:
    print("*" * n)
    pattern(n-1)

Enter a number: 5
*****
****
***
**
*


Inch to cm function

In [ ]:
n = int(input("Enter inch: "))

def cm_fun(inch):
  cm = inch * 2.54
  print(f"{inch} inch = {cm} cm")

cm_fun(n)

Enter inch: 5
5 inch = 12.7 cm


Remove a given word from the list and strip it at the same time

In [ ]:
animals = ["Cat", "Dog", "Rat", "Parrot"]

word = "t"

def rem(l, word):
  new_list = []
  for item in l:
    if not item == word:
      new_list.append(item.strip(word))
  return new_list

rem(animals, word)


['Ca', 'Dog', 'Ra', 'Parro']

Function to print multiplication table

In [ ]:
n = int(input("Enter a number: "))

def tables(n):
  print(f"Tables of {n}")
  for i in range(1,11):
    print(f"{n} X {i} = {n*i}")

tables(n)

Enter a number: 5
Tables of 5
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50


**Snake Water Gun Game**

In [ ]:
import random

computer = random.choice([0, -1, 1])
youstr = input("Enter your choice: ")
youDict = {"s":1, "w":-1, "g":0}
reverseDict = {1:"Snake", -1:"Water", 0:"Gun"}
you = youDict[youstr]

print(f"You chose {reverseDict[you]} \nComputer chose {reverseDict[computer]}")

if(computer == you):
  print("It's a Draw")
else:
  if(computer == 1 and you == 0):
    print("You Win")
  elif(computer == 1 and you == -1):
    print("Computer Won")
  elif(computer == 0 and you == 1):
    print("Computer Won")
  elif(computer == 0 and you == -1):
    print("You Won")
  elif(computer == -1 and you == 0):
    print("Computer Won")
  elif(computer == -1 and you == 1):
    print("You Won")
  else:
    print("Something went wrong")

Enter your choice: w
You chose Water 
Computer chose Snake
Computer Won


Same game with lil number of lines

In [ ]:
import random

computer = random.choice([0, -1, 1])
youstr = input("Enter your choice: ")
youDict = {"s":1, "w":-1, "g":0}
reverseDict = {1:"Snake", -1:"Water", 0:"Gun"}
you = youDict[youstr]

print(f"You chose {reverseDict[you]} \nComputer chose {reverseDict[computer]}")
if(computer == you):
  print("It's a Draw")
else:
  if((computer-you) == -1 or (computer-you) == 2): #This logic is written in the basis of Computer - You Computation.
    print("Computer Won")
  else:
    print("You Won")


Enter your choice: s
You chose Snake 
Computer chose Water
You Won


Opening a file

In [ ]:
f = open("file.txt")
data = f.read()
print(data)
f.close()
#Run this in VS code

**Chapter 10- OOP**

Basic Class Implementation


In [ ]:
class Employee:
  name = "Harry"
  lang = "Py"
  salary = 1200000

harry = Employee()
print(harry.name, harry.lang)

Harry Py


Practice Set

Create a Class of Programmer

In [ ]:
class Programmer:
  def __init__(self, name, lang, salary):
    self.name = name
    self.lang = lang
    self.salary = salary

emp1 = Programmer("Zabi", "Python", 100000)
print(emp1.name, emp1.lang, emp1.salary)

emp2 = Programmer("Musab", "Java", 200000)
print(emp2.name, emp2.lang, emp2.salary)

emp3 = Programmer("Tom", "C++", 300000)
print(emp3.name, emp3.lang, emp3.salary)

Zabi Python 100000
Musab Java 200000
Tom C++ 300000


Create a class Calculator to find square, cube and square root of a number

In [ ]:
class Calculator:
  def __init__(self, num):
    self.num = num

  def square(self):
    print(f"Square of {self.num} is {self.num**2}")

  def cube(self):
    print(f"Cube of {self.num} is {self.num**3}")

  def sqrt(self):
    print(f"Square root of {self.num} is {self.num**0.5}")

  @staticmethod
  def Greeting():
    print("Hello")

num1 = Calculator(10)
num1.square()
num1.cube()
num1.sqrt()

Square of 10 is 100
Cube of 10 is 1000
Square root of 10 is 3.1622776601683795


In [ ]:
class Sample:
  a = "Hello"

eg1 = Sample()
eg1.a = "Hi"

print(eg1.a)

Hi


Ticket booking class

In [ ]:
from random import randint

class Train:
  def __init__(self, TrainNo):
    self.TrainNo = TrainNo

  def book(self, fro, to):
    print(f"The Train No {self.TrainNo} is booked from {fro} to {to}")
  def getStatus(self):
    print(f"Train No {self.TrainNo} is running on time.")
  def getFare(self, fro, to):
    print(f"Fare for Train No {self.TrainNo} from {fro} to {to} is {randint(222,555)}")

t = Train(1234)
t.book("VNb", "Blr")
t.getStatus()
t.getFare("VNb", "Blr")

The Train No 1234 is booked from VNb to Blr
Train No 1234 is running on time.
Fare for Train No 1234 from VNb to Blr is 405


**Chapter 11 - Inheritance and more**

Example on Multiple Inheritance

In [ ]:
class Employee:
  company = "TCS"

  def show(self):
    print("Hi, this is a Emplyee class function!")

class Coder:
  def __init__(self, name):
    self.name = name

  def lang(self, language):
    print(f"I'm {self.name}, and I'm a {language} developer")

class Programmer(Employee, Coder):
  def Experience(self, time):
    print(f"I'm working on this for {time} years")

emp1 = Programmer("Zabi")
emp1.show()
emp1.lang("Python")
emp1.Experience(5)

Hi, this is a Emplyee class function!
I'm Zabi, and I'm a Python developer
I'm working on this for 5 years


**Chapter 11 - Practice Set**

1) Create a class (2-D vector) and use it to vrate another class representing a 3-D vector

In [ ]:
class TwoDVector:
  def __init__(self, x, y):
    self.x = x
    self.y = y
  def show(self):
    print(f"{self.x}x, {self.y}y")

class ThreeDVector(TwoDVector):
  def __init__(self, x, y, z):
    super().__init__(x, y)
    self.z = z
  def show(self):
    print(f"{self.x}x, {self.y}y, {self.z}z")

a = ThreeDVector(1,2,3)
a.show()

1x, 2y, 3z


Create a class pets
from a class Animals
create class dog from pets
Add method "Bark" to class "dog"

In [ ]:
class Animals:
    def __init__(self, type, age, name):  # No @property here
        self.name = name
        self.type = type
        self.age = age

    def display(self):
        print(f"It is a {self.name}, which is a {self.type} animal of {self.age} years.")

class Pets(Animals):
    def __init__(self, petname, name, type, age):
        super().__init__(type, age, name)  # Proper call to base class constructor
        self.petname = petname

    def show(self):
        print(f"My {self.petname} is a good {self.name}")

class Dog(Pets):
    @staticmethod
    def bark():
        print("Dog barks!")

# Test the classes
b = Animals("Domestic", 10, "Dog")
b.display()

a = Pets("Tara", "Dog", "Domestic", 10)
a.show()

Dog.bark()


It is a Dog, which is a Domestic animal of 10 years.
My Tara is a good Dog
Dog barks!


In [ ]:
class Employee:
    salary = 234
    increment = 20

    @property
    def salaryAfterIncrement(self):
        return (self.salary + self.salary *(self.increment/100))

    @salaryAfterIncrement.setter
    def salaryAfterIncrement(self, salary):
        self.increment = ((salary/self.salary) -1)*100

e = Employee()
e.salaryAfterIncrement = 280.8
print(e.increment)

19.999999999999996


In [ ]:
class complex:
    def __init__(self, i, j, op):
        self.i = i
        self.j = j
        self.op = op

    def show(self):
        print(f"Complex number is: {self.i} {self.op} {self.j}j")

c = complex(2,5,"-")
c.show()

Complex number is: 2 - 5j


In [ ]:
class Complex:
    def __init__(self, r, i):
        self.r = r
        self.i = i

    def __add__(self, c2):
        return Complex(self.r +c2.r, self.i +c2.i)

    def __mul__(self, c2):
        real_part = self.r * c2.r - self.i * c2.i
        imag_part = self.r * c2.i + self.i * c2.r
        return Complex(real_part, imag_part)

    def __str__(self):
        return f"{self.r} + {self.i}i"

c1 = Complex(1, 2)
c2 = Complex(3, 4)
print(c1 + c2)
print(c1 * c2)

4 + 6i
-5 + 10i


You're doing a great job applying **Object-Oriented Programming (OOP)** in Python — this time with **operator overloading** using `__add__`, `__mul__`, and `__str__`. Let me explain your program **line by line**:

---

### 🔢 Class: `Complex`

You’re defining a class to handle **complex numbers** (of the form `a + bi`).

---

### 1. **Constructor: `__init__`**

```python
def __init__(self, r, i):
    self.r = r
    self.i = i
```

* This initializes a complex number with:

  * `r`: real part
  * `i`: imaginary part
* Example: `Complex(1, 2)` → 1 + 2i

---

### 2. **Operator Overloading: `__add__`**

```python
def __add__(self, c2):
    return Complex(self.r + c2.r, self.i + c2.i)
```

* Allows the use of `+` between two `Complex` objects.
* Adds:

  * real parts: `self.r + c2.r`
  * imaginary parts: `self.i + c2.i`
* Returns a **new Complex object** with the sum.

---

### 3. **Operator Overloading: `__mul__`**

```python
def __mul__(self, c2):
    real_part = self.r * c2.r - self.i * c2.i
    imag_part = self.r * c2.i + self.i * c2.r
    return Complex(real_part, imag_part)
```

* Allows the use of `*` between two `Complex` objects.
* Follows the formula for complex multiplication:

  $$
  (a + bi)(c + di) = (ac - bd) + (ad + bc)i
  $$
* Returns a new `Complex` object with the product.

---

### 4. **String Representation: `__str__`**

```python
def __str__(self):
    return f"{self.r} + {self.i}i"
```

* This makes `print(c1)` output something readable like `1 + 2i`.

---

### 5. **Testing the Class**

```python
c1 = Complex(1, 2)
c2 = Complex(3, 4)
print(c1 + c2)
print(c1 * c2)
```

#### Let's break down:

**Addition:**

```python
(1 + 2i) + (3 + 4i) = (1+3) + (2+4)i = 4 + 6i
```

**Multiplication:**

```python
(1 + 2i) * (3 + 4i)
= 1*3 - 2*4 + (1*4 + 2*3)i
= 3 - 8 + (4 + 6)i
= -5 + 10i
```

### ✅ Output:

```
4 + 6i
-5 + 10i
```

---

### 🔁 Summary of Key Concepts Used:

| Concept               | Usage in Code                                     |
| --------------------- | ------------------------------------------------- |
| Class & Objects       | `Complex` class                                   |
| Constructor           | `__init__`                                        |
| Operator Overloading  | `__add__`, `__mul__`                              |
| String Representation | `__str__`                                         |
| Abstraction           | Hiding how addition/multiplication is implemented |

---

Would you like me to give you a small challenge to practice this?


In [ ]:
class Vector:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

    def __add__(self, other):
        result = Vector(self.x + other.x, self.y + other.y, self.z +other.z)
        return result

    def __mul__(self, other):
        result = self.x * other.x + self.y * other.y +self.z *other.z
        return result

    def __str__(self):
        return f"Vector({self.x}, {self.y}, {self.z})"

v1 = Vector(1, 2, 3)
v2 = Vector(4, 5 ,6)
v3 = Vector(7, 8, 9)

print(v1 + v2)
print(v1 * v2)

print(v1 + v3)
print(v1 * v3)

Vector(5, 7, 9)
32
Vector(8, 10, 12)
50


Great job! 🎯 You’ve created a solid implementation of a **3D vector class** using **operator overloading** in Python. Let’s walk through and explain what your program is doing:

---

## ✅ Your Code Breakdown:

### 🔸 1. `__init__` – Constructor

```python
def __init__(self, x, y, z):
    self.x = x
    self.y = y
    self.z = z
```

* Initializes a `Vector` object with 3 components: `x`, `y`, and `z`.

---

### 🔸 2. `__add__` – Vector Addition

```python
def __add__(self, other):
    result = Vector(self.x + other.x, self.y + other.y, self.z + other.z)
    return result
```

* Adds two vectors **component-wise**:

  $$
  (x_1 + x_2, y_1 + y_2, z_1 + z_2)
  $$
* Returns a new `Vector` instance.

---

### 🔸 3. `__mul__` – Dot Product

```python
def __mul__(self, other):
    result = self.x * other.x + self.y * other.y + self.z * other.z
    return result
```

* Performs **dot product**:

  $$
  x_1 \cdot x_2 + y_1 \cdot y_2 + z_1 \cdot z_2
  $$
* Returns a **scalar (number)**.

---

### 🔸 4. `__str__` – String Representation

```python
def __str__(self):
    return f"Vector({self.x}, {self.y}, {self.z})"
```

* Allows `print(vector)` to output a clean string like `Vector(1, 2, 3)` instead of an object reference.

---

### 🧪 Test Output:

#### Vector Addition:

```python
v1 + v2 = Vector(1+4, 2+5, 3+6) = Vector(5, 7, 9)
v1 + v3 = Vector(1+7, 2+8, 3+9) = Vector(8, 10, 12)
```

#### Dot Product:

```python
v1 * v2 = 1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32
v1 * v3 = 1*7 + 2*8 + 3*9 = 7 + 16 + 27 = 50
```

---

### ✅ Final Output:

```
Vector(5, 7, 9)
32
Vector(8, 10, 12)
50
```

---

## 🌟 Concepts You Used

| Concept              | Usage in Code                |
| -------------------- | ---------------------------- |
| OOP                  | `Vector` class and instances |
| Constructor          | `__init__`                   |
| Operator Overloading | `__add__`, `__mul__`         |
| Encapsulation        | Attributes `x, y, z`         |
| Dot Product Logic    | `__mul__`                    |
| Code Reusability     | Object-based design          |

---

### 💡 Want to Try More?

Here's a small **challenge**:

> Add a method to compute the **cross product** of two vectors:

```python
def cross(self, other):
    # return Vector(...)
```

Would you like help implementing that?


In [ ]:
class ComplexNo:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

    def show(self):
        print(f"{self.x}i + {self.y}j + {self.z}k")

a = ComplexNo(1, 2, 3)
a.show()

1i + 2j + 3k


To find length of a vector

In [ ]:
class V:
    def __init__(self, l):
        self.l = l

    def __len__(self):
        return len(self.l)

v1 = V([1, 2, 3])
print(len(v1))

3


You're absolutely right with this one! ✅
Let’s walk through what you’ve done in this code:

---

### 🔍 Code Explanation

```python
class Vector:
    def __init__(self, l):
        self.l = l
```

* You define a class `Vector` that takes a list `l` (e.g., `[1, 2, 3]`) and stores it as an instance variable.

---

```python
def __len__(self):
    return len(self.l)
```

* This overrides Python’s built-in `len()` function for your custom class.
* So when you call `len(v1)`, it returns the length of the list inside `v1.l`.

---

### ✅ Test Code

```python
v1 = Vector([1, 2, 3])
print(len(v1))
```

### 🧾 Output:

```
3
```

✅ This is **correct and clean**.

---

### 💡 Bonus Tip:

You can also add other overloads like:

* `__getitem__` to access elements (`v1[0]`)
* `__str__` for pretty printing (`print(v1)`)
* `__iter__` to make your object iterable in a loop

Want help adding those too?


Game 2 : Guess Random Number

In [ ]:
import random
n = random.randint(1, 100)
a = -1
guesses = 1
while(a != n):
    a = int(input("Guess the number: "))
    if(a > n):
        print("Lower number please")
        guesses += 1
    elif(a < n):
        print("Higher number please")
        guesses += 1
print(f" You have guessed the numberr {n} correctly in {guesses} attempts")

Guess the number: 6
Higher number please
Guess the number: 56
Lower number please
Guess the number: 40
Lower number please
Guess the number: 30
Lower number please
Guess the number: 20
Higher number please
Guess the number: 25
Lower number please
Guess the number: 23
 You have guessed the numberr 23 correctly in 7 attempts


**Chapter 12 - Advanced Pythn concepts**
New Added Features

Using Walrus Operator (added in python 3.8)

In [ ]:
if (n := len([1, 2, 3, 4, 5])) > 3:
    print(f"Length of {n} is greater than 3")

Length of 5 is greater than 3


Great! Let’s break it down into two parts as you asked:

---

## 🦦 1. **Walrus Operator (`:=`) in Python**

The **walrus operator** (`:=`) is used for **assignment expressions** — it lets you assign a value to a variable **within an expression**.

### ✅ Use Case:

Before Python 3.8, you’d need:

```python
value = input("Enter something: ")
while value != "exit":
    print(f"You entered: {value}")
    value = input("Enter something: ")
```

With the **walrus operator**:

```python
while (value := input("Enter something: ")) != "exit":
    print(f"You entered: {value}")
```

### 💡 Use Cases:

* Shorten `while`, `if`, and list comprehensions
* Reduce redundancy when you need to **use a value and test it** in one step

---

## 🧾 2. **Type Definitions and Type Hints**

Type hints help you define **what type of data** your variables, function arguments, and return values should be. This improves **code readability** and helps with **debugging and IDE suggestions**.

### ✅ Example:

```python
def add(x: int, y: int) -> int:
    return x + y

def greet(name: str) -> None:
    print(f"Hello, {name}")
```

---

### 🧰 Type Definitions in Variables:

```python
age: int = 21
pi: float = 3.14
names: list[str] = ["Zabi", "Ali", "Sara"]
user: dict[str, int] = {"id": 101}
```

### ✅ Type Hints in Classes and Methods:

```python
class Vector:
    def __init__(self, x: float, y: float, z: float) -> None:
        self.x = x
        self.y = y
        self.z = z

    def magnitude(self) -> float:
        return (self.x**2 + self.y**2 + self.z**2) ** 0.5
```

---

### 💡 Advanced: Using `typing` Module

```python
from typing import List, Dict, Union

def process_scores(scores: List[int]) -> float:
    return sum(scores) / len(scores)
```

---

### ✅ Summary Table:

| Concept           | Syntax / Example                   |
| ----------------- | ---------------------------------- |
| Walrus operator   | `while (x := input()) != "q": ...` |
| Function hint     | `def foo(x: int) -> str:`          |
| Variable hint     | `score: float = 92.5`              |
| List/Dict hint    | `List[int]`, `Dict[str, int]`      |
| Class method hint | `def method(self) -> None:`        |

---

Would you like practice questions on walrus operator or type hinting?


In [ ]:
def sum(a:int, b:int) -> int:
    return a+b

add = sum(10, 20)
print(add)

30


Match Case (Python 3.10)

In [ ]:
def status(a):
    match a:
        case 10:
            return "10"
        case 20:
            return "20"
        case 30:
            return "30"
        case _:
            return "Tata"
print(status(40))

Tata


Dictionary Merge and Update Opertors

Merge (|) and Update (|=)

Sure, Zabi! Here's a simple and clear guide on **Dictionary Merge and Update Operators** in Python, with key points, examples, and practice questions.

---

## 📘 **Dictionary Merge and Update in Python**

### ✅ 1. **Using `update()` Method**

* Merges one dictionary into another.
* Updates the existing keys or adds new ones.
* Original dictionary gets modified.

```python
d1 = {'a': 1, 'b': 2}
d2 = {'b': 3, 'c': 4}
d1.update(d2)
print(d1)  # {'a': 1, 'b': 3, 'c': 4}
```

---

### ✅ 2. **Using Merge (`|`) Operator** *(Python 3.9+)*

* Returns a **new merged dictionary**.
* Doesn’t modify the original ones.

```python
d1 = {'x': 1, 'y': 2}
d2 = {'y': 100, 'z': 200}
d3 = d1 | d2
print(d3)  # {'x': 1, 'y': 100, 'z': 200}
```

---

### ✅ 3. **Using Update Merge (`|=`) Operator** *(Python 3.9+)*

* Merges `d2` into `d1` and updates `d1` in-place.

```python
d1 = {'name': 'Zabi'}
d2 = {'age': 21}
d1 |= d2
print(d1)  # {'name': 'Zabi', 'age': 21}
```

---

## 🔑 **Important Points**

\| Feature                | `update()` | `|` Operator | `|=` Operator |
\|------------------------|------------|--------------|----------------|
\| Modifies original dict | ✅ Yes     | ❌ No         | ✅ Yes         |
\| Returns new dict       | ❌ No      | ✅ Yes        | ❌ No          |
\| Available from version | All Python | Python 3.9+   | Python 3.9+    |

---

## 🧪 Example

```python
user1 = {'id': 101, 'name': 'Zabi'}
user2 = {'name': 'Zabir', 'age': 22}

# Merge using |
merged = user1 | user2
print(merged)  # {'id': 101, 'name': 'Zabir', 'age': 22}

# Update using update()
user1.update(user2)
print(user1)  # {'id': 101, 'name': 'Zabir', 'age': 22}
```

---

## 🧩 Practice Questions

### 📝 Q1:

```python
d1 = {'a': 10, 'b': 20}
d2 = {'b': 50, 'c': 30}
# Merge using | operator
```

➡️ What will be the result?

---

### 📝 Q2:

```python
info = {'name': 'Zara'}
extra = {'age': 19, 'name': 'Zabi'}

# Use update() to merge
```

➡️ What will be the final value of `info`?

---

Would you like the answers to these or more practice sets?


In [ ]:
d1 = {'a': 10, 'b': 20}
d2 = {'b': 50, 'c': 30}
# Merge using | operator

d3 = d1|d2
print(d3)

{'a': 10, 'b': 50, 'c': 30}


In [ ]:
info = {'name': 'Zara'}
extra = {'age': 19, 'name': 'Zabi'}

# Use update() to merge
print("Before merge")
print(info,extra)
print("After merge")
info.update(extra)
print(info)

Before merge
{'name': 'Zara'} {'age': 19, 'name': 'Zabi'}
After merge
{'name': 'Zabi', 'age': 19}


In [ ]:
info = {'name': 'Zara'}
extra = {'age': 19, 'name': 'Zabi'}

info |= extra
print(info)

{'name': 'Zabi', 'age': 19}


Exception Handling

In [ ]:
try:
    a = int(input("Enter a num: "))
    print(a)
except Exception as e:
    print(e)
print("End of Code")

Enter a num: hi
invalid literal for int() with base 10: 'hi'
End of Code


Raising Exceptions

In [ ]:
a = int(input("Enter 1 number:"))
b = int(input("Enter 2 number:"))

if(b == 0):
    raise ZeroDivisionError("Hey, Division by zero is not possible!!!")
else:
    print(f"{a}/{b} is {a/b}")

Enter 1 number:30
Enter 2 number:2
30/2 is 15.0


Try with finally

In [ ]:
def main():
    try:
        a = int(input("Enter a: "))
        return
    except Exception as e:
        print(e)
        return
    finally:
        print("Finally part...")
main( )



Enter a: a
invalid literal for int() with base 10: 'a'
Finally part...


Enumerate in python

You're absolutely right to ask this — it's an excellent question that shows you're thinking deeper about how Python works! Let's break it down in the **simplest way possible**.

---

## 🧠 What is `enumerate()` in Python?

The **`enumerate()` function** adds a **counter (index)** to an **iterable** like a list, tuple, or string.
It returns a **special object** that contains pairs of:

```
(index, value)
```

---

### 🛠️ Basic Syntax:

```python
enumerate(iterable, start=0)
```

* `iterable`: list, tuple, string, etc.
* `start`: index to start counting from (default is 0)

---

### 🧪 Example:

```python
l = ['a', 'b', 'c']
for index, value in enumerate(l):
    print(index, value)
```

### 🔍 Output:

```
0 a
1 b
2 c
```

Here, `enumerate(l)` returns:

```python
[(0, 'a'), (1, 'b'), (2, 'c')]
```

Then, `for index, value in ...` unpacks each `(index, value)` pair from that list.

---

### 🧠 Your Exact Question Answered:

> **"How does `enumerate` know that I'm calling `index` and `item`?"**

➡️ It **doesn’t know**!
`index` and `item` are **just variable names** you chose.

Python looks at the output of `enumerate(l)` which is a series of `(index, value)` pairs, like:

```python
(0, 3)
(1, 4)
(2, 5)
(3, 6)
```

Then, when you write:

```python
for index, item in enumerate(l):
```

You're telling Python:

* "Take each pair and unpack it: assign the first thing to `index`, second to `item`."

You could rename them to anything:

```python
for i, val in enumerate(l):
    print(i, val)
```

Still works the same.

---

## 🔄 How is it Different from Just a Loop?

Without `enumerate()`:

```python
for i in range(len(l)):
    print(i, l[i])
```

With `enumerate()`:

```python
for i, item in enumerate(l):
    print(i, item)
```

➡️ Cleaner, more Pythonic, and **avoids indexing errors**.

---

## 💡 Bonus: Using `start` Argument

```python
for i, val in enumerate(['x', 'y', 'z'], start=1):
    print(i, val)
```

**Output:**

```
1 x
2 y
3 z
```

---

## ✅ Summary

| Concept         | Meaning                                  |
| --------------- | ---------------------------------------- |
| `enumerate()`   | Adds index to iterable                   |
| Output          | `(index, value)` pairs                   |
| `index`, `item` | Just variable names you choose           |
| Cleaner?        | YES. Better than using `range(len(...))` |

---

Would you like a small challenge or a visual illustration of how `enumerate` works?


In [ ]:
l = [3, 4, 5 ,6]

for i, item in enumerate(l,1):
    print(i, item)

1 3
2 4
3 5
4 6


**Chapter 12 - Practice set**

program to open 3 files...

If any of the files don't open, print a message without exiting the program

printed prompting the same



above program was done in vs code


printing third, fifth and 7th element in a list using enumerate()

In [ ]:
l = [10, 20, 30, 40, 50, 60, 70, 80, 90]

for i, item in enumerate(l):
    print(i, item)

0 10
1 20
2 30
3 40
4 50
5 60
6 70
7 80
8 90


In [ ]:
l = [10, 20, 30, 40, 50, 60, 70, 80, 90]
for i, item in enumerate(l):
    if(i > 1 and i%2 == 0):
        print(i+1, item)
    else:
        pass

3 30
5 50
7 70
9 90


3. Write a list comprehension to print a list which contains the multiplication table of a
user entered number.

In [ ]:
li = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
n = int(input("Enter a num: "))
tables = [i*n for i in li]
print(tables)

Enter a num: 4
[4, 8, 12, 16, 20, 24, 28, 32, 36, 40]


4. Write a program to display a/b where a and b are integers. If b=0, display infinite by
handling the ‘ZeroDivisionError’.


In [ ]:
a = int(input("Enter a number: "))
b = int(input("Enter a number: "))

try:
    print(f"a/b is {a/b}")
except Exception as ZeroDivisionError:
    print("Infinite")
finally:
    print("I'm always printed!!!cuz I'm a part of finally block\nHappy coding")

Enter a number: 2
Enter a number: 0
Infinite
I'm always printed!!!cuz I'm a part of finally block
Happy coding


5. Store the multiplication tables generated in problem 3 in a file named Tables.txt

Done in vs code

#Hacker Rank Problems

In [ ]:
def swap_case(s):
    return s.swapcase()

if __name__ == '__main__':
    s = input()
    result = swap_case(s)
    print(result)

Hi
hI


In [ ]:
def split_and_join(line):
    # write your code here
    line = line.split(" ")
    line = "-".join(line)
    return line

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

In [ ]:
def count_substring(string, sub_string):
    count = 0
    for i in range(len(string) - len(sub_string)+1):
        if(string[i: i+len(sub_string)] == sub_string):
            count += 1
    return count

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()

    count = count_substring(string, sub_string)
    print(count)

abcbc
bc
2


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:

arr = np.array(np.random.randint([n]))
arr

array([0, 3])

In [ ]:
import numpy as np

arr = np.arange(1, 11)  # Cleaner alternative
print("1D Array from 1 to 10:", arr)


1D Array from 1 to 10: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np

arr = np.arange(1, 10).reshape(3, 3)  # Cleaner and dynamic
print("3x3 Matrix:")
print(arr)


3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np

# Create a 3x3 matrix with numbers 1 to 9
matrix = np.arange(1, 10).reshape(3, 3)

print("Matrix:")
print(matrix)

# Transpose it
print("Transposed Matrix:")
print(matrix.T)

# Sum of all elements
print("Sum:", matrix.sum())


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum: 45


In [ ]:
def checkOddEven(x):
    if x % 2 == 0:
        return "Even"
    else:
        return "Odd"

x = int(input())
print(checkOddEven(x))


1
Odd


In [ ]:
d = dict({'x':123, 'y':354})
for i in d:
    print("%s  %d" % (i, d[i]))

x  123
y  354


In [ ]:
for letter in 'geeksforgeeks':
    if letter == 'e' or letter == 's':
        break

print('Current Letter :', letter)

Current Letter : e


In [ ]:
fruits = ["apple", "orange", "kiwi"]
iter_obj = iter(fruits)
while True:
    try:
        fruit = next(iter_obj)
        print(fruit)
    except StopIteration:
        break

apple
orange
kiwi
